### ISSUE TITLE
Vfs

### ISSUE THREAD

**Issue by Shamulina96** [flavves/make-appointment-vfsglobal#1]
Здравствуйте. Подскажите, пожалуйста, работает ли эта программа в белорусском вц?

**Comment by flavves** [comment]
I dont understand you. Please write in English

**Comment by Shamulina96** [comment]
Tell me please,  if this script is suitable for the visa application
center of Poland in Belarus


чт, 7 июл. 2022 г., 20:11 Batuhan ÖKMEN ***@***.***>:

> I dont understand you. Please write in English
>

**Comment by flavves** [comment]
This program need to be update. Thees days i cant do it. You can text me on
telegram flavves
